services:
  web:
    image: beratech
    container_name: beratech
    build:
      context: ../beratech
      dockerfile: ../beratech/Dockerfile
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - pgnetwork
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin:z
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  pgdata:
  pgadmindata: